[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-inject-env-vars"
  [plugins.inputs]
    environment = "production"

[build.environment]
  NODE_VERSION = "18"
